[2021-03-23 19:29:00,453] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: Model-Training-Pipeline.TrainBertModel 2021-03-23T23:28:27.221663+00:00 [queued]>
[2021-03-23 19:29:00,507] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: Model-Training-Pipeline.TrainBertModel 2021-03-23T23:28:27.221663+00:00 [queued]>
[2021-03-23 19:29:00,507] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 19:29:00,507] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-23 19:29:00,507] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 19:29:00,538] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): TrainBertModel> on 2021-03-23T23:28:27.221663+00:00
[2021-03-23 19:29:00,544] {standard_task_runner.py:52} INFO - Started process 13676 to run task
[2021-03-23 19:29:00,570] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Model-Training-Pipeline', 'TrainBertModel', '2021-03-23T23:28:27.221663+00:00', '--job-id', '35', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/train.py', '--cfg-path', '/var/folders/j6/755w2l7n4x1c9313788klj880000gq/T/tmphxlfsxat', '--error-file', '/var/folders/j6/755w2l7n4x1c9313788klj880000gq/T/tmp0sm38cfe']
[2021-03-23 19:29:00,572] {standard_task_runner.py:77} INFO - Job 35: Subtask TrainBertModel
[2021-03-23 19:29:00,672] {logging_mixin.py:104} INFO - Running <TaskInstance: Model-Training-Pipeline.TrainBertModel 2021-03-23T23:28:27.221663+00:00 [running]> on host 152.1.168.192.in-addr.arpa
[2021-03-23 19:29:00,768] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Model-Training-Pipeline
AIRFLOW_CTX_TASK_ID=TrainBertModel
AIRFLOW_CTX_EXECUTION_DATE=2021-03-23T23:28:27.221663+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-23T23:28:27.221663+00:00
[2021-03-23 19:29:00,806] {logging_mixin.py:104} INFO - Found 7 files belonging to 2 classes.
[2021-03-23 19:29:00,907] {logging_mixin.py:104} INFO - Using 6 files for training.
[2021-03-23 19:29:01,144] {logging_mixin.py:104} INFO - Found 7 files belonging to 2 classes.
[2021-03-23 19:29:01,244] {logging_mixin.py:104} INFO - Using 1 files for validation.
[2021-03-23 19:29:01,256] {logging_mixin.py:104} INFO - Found 2 files belonging to 2 classes.
[2021-03-23 19:29:01,372] {logging_mixin.py:104} INFO - BERT model selected: https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-4_H-512_A-8/1
[2021-03-23 19:29:01,372] {logging_mixin.py:104} INFO - Preprocess model auto-selected: https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3
[2021-03-23 19:29:01,385] {resolver.py:106} INFO - Using /var/folders/j6/755w2l7n4x1c9313788klj880000gq/T/tfhub_modules to cache modules.
[2021-03-23 19:29:40,532] {optimization.py:89} INFO - using Adamw optimizer
[2021-03-23 19:29:40,535] {optimization.py:142} INFO - gradient_clip_norm=1.000000
[2021-03-23 19:29:40,549] {logging_mixin.py:104} INFO - Training model with https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-4_H-512_A-8/1
[2021-03-23 19:30:00,374] {logging_mixin.py:104} INFO - 1/1 [==============================] - ETA: 0s - loss: 0.7497 - binary_accuracy: 0.5000
[2021-03-23 19:30:05,516] {logging_mixin.py:104} INFO - 1/1 [==============================] - 25s 25s/step - loss: 0.7497 - binary_accuracy: 0.5000 - val_loss: 0.4547 - val_binary_accuracy: 1.0000
[2021-03-23 19:30:05,845] {logging_mixin.py:104} INFO - 1/1 [==============================] - ETA: 0s - loss: 0.5122 - binary_accuracy: 0.5000
[2021-03-23 19:30:05,847] {logging_mixin.py:104} INFO - 1/1 [==============================] - 0s 324ms/step - loss: 0.5122 - binary_accuracy: 0.5000
[2021-03-23 19:30:05,850] {logging_mixin.py:104} INFO - Loss: 0.5122100710868835
[2021-03-23 19:30:05,851] {logging_mixin.py:104} INFO - Accuracy: 0.5
[2021-03-23 19:30:05,852] {taskinstance.py:1455} ERROR - name 'config' is not defined
Traceback (most recent call last):
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/dags/train.py", line 335, in train_model
    saved_model_path = config["dev"]['saved_model_path']
NameError: name 'config' is not defined
[2021-03-23 19:30:05,856] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=Model-Training-Pipeline, task_id=TrainBertModel, execution_date=20210323T232827, start_date=20210323T232900, end_date=20210323T233005
[2021-03-23 19:30:06,193] {local_task_job.py:188} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2021-03-23 19:30:06,213] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 13676
