[2021-03-23 15:58:08,790] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.DownloadDataFromCloud 2021-03-23T22:57:46.265225+00:00 [queued]>
[2021-03-23 15:58:08,794] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.DownloadDataFromCloud 2021-03-23T22:57:46.265225+00:00 [queued]>
[2021-03-23 15:58:08,794] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 15:58:08,794] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-23 15:58:08,794] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 15:58:08,800] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): DownloadDataFromCloud> on 2021-03-23T22:57:46.265225+00:00
[2021-03-23 15:58:08,802] {standard_task_runner.py:52} INFO - Started process 40337 to run task
[2021-03-23 15:58:08,810] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EDGAR-Annotation-Pipeline', 'DownloadDataFromCloud', '2021-03-23T22:57:46.265225+00:00', '--job-id', '63', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/edgar_annotation.py', '--cfg-path', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpp1v87w_x', '--error-file', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpilar_t7b']
[2021-03-23 15:58:08,812] {standard_task_runner.py:77} INFO - Job 63: Subtask DownloadDataFromCloud
[2021-03-23 15:58:08,840] {logging_mixin.py:104} INFO - Running <TaskInstance: EDGAR-Annotation-Pipeline.DownloadDataFromCloud 2021-03-23T22:57:46.265225+00:00 [running]> on host prathyushas-mbp.home
[2021-03-23 15:58:08,862] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EDGAR-Annotation-Pipeline
AIRFLOW_CTX_TASK_ID=DownloadDataFromCloud
AIRFLOW_CTX_EXECUTION_DATE=2021-03-23T22:57:46.265225+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-23T22:57:46.265225+00:00
[2021-03-23 15:58:08,900] {credentials.py:1222} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2021-03-23 15:58:20,885] {python.py:118} INFO - Done. Returned value was: None
[2021-03-23 15:58:20,890] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=EDGAR-Annotation-Pipeline, task_id=DownloadDataFromCloud, execution_date=20210323T225746, start_date=20210323T225808, end_date=20210323T225820
[2021-03-23 15:58:20,906] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-23 15:58:20,944] {local_task_job.py:146} INFO - Task exited with return code 0
