[2021-03-23 20:27:42,346] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: Model-Training-Pipeline.SaveModel 2021-03-24T00:25:38.944447+00:00 [queued]>
[2021-03-23 20:27:42,372] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: Model-Training-Pipeline.SaveModel 2021-03-24T00:25:38.944447+00:00 [queued]>
[2021-03-23 20:27:42,373] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 20:27:42,373] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-23 20:27:42,373] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 20:27:42,394] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): SaveModel> on 2021-03-24T00:25:38.944447+00:00
[2021-03-23 20:27:42,401] {standard_task_runner.py:52} INFO - Started process 14358 to run task
[2021-03-23 20:27:42,419] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Model-Training-Pipeline', 'SaveModel', '2021-03-24T00:25:38.944447+00:00', '--job-id', '45', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/train.py', '--cfg-path', '/var/folders/j6/755w2l7n4x1c9313788klj880000gq/T/tmpijmofmrq', '--error-file', '/var/folders/j6/755w2l7n4x1c9313788klj880000gq/T/tmp_kngdfyq']
[2021-03-23 20:27:42,425] {standard_task_runner.py:77} INFO - Job 45: Subtask SaveModel
[2021-03-23 20:27:42,506] {logging_mixin.py:104} INFO - Running <TaskInstance: Model-Training-Pipeline.SaveModel 2021-03-24T00:25:38.944447+00:00 [running]> on host 152.1.168.192.in-addr.arpa
[2021-03-23 20:27:42,569] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Model-Training-Pipeline
AIRFLOW_CTX_TASK_ID=SaveModel
AIRFLOW_CTX_EXECUTION_DATE=2021-03-24T00:25:38.944447+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-24T00:25:38.944447+00:00
[2021-03-23 20:27:42,861] {taskinstance.py:1455} ERROR - [Errno 21] Is a directory: './EDGARModel_bert'
Traceback (most recent call last):
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/dags/train.py", line 353, in save_model
    s3.Bucket(bucket).upload_file(filepath,'{}'.format(s3_target))
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/boto3/s3/inject.py", line 209, in bucket_upload_file
    ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/boto3/s3/inject.py", line 131, in upload_file
    extra_args=ExtraArgs, callback=Callback)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/boto3/s3/transfer.py", line 279, in upload_file
    future.result()
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/s3transfer/upload.py", line 692, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/botocore/client.py", line 657, in _make_api_call
    request_signer=self._request_signer, context=request_context)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/botocore/hooks.py", line 360, in emit_until_response
    return self._emitter.emit_until_response(aliased_event_name, **kwargs)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/botocore/hooks.py", line 243, in emit_until_response
    responses = self._emit(event_name, kwargs, stop_on_response=True)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/botocore/utils.py", line 2262, in conditionally_calculate_md5
    md5_digest = calculate_md5(body, **kwargs)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/botocore/utils.py", line 2239, in calculate_md5
    binary_md5 = _calculate_md5_from_file(body)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/botocore/utils.py", line 2251, in _calculate_md5_from_file
    for chunk in iter(lambda: fileobj.read(1024 * 1024), b''):
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/botocore/utils.py", line 2251, in <lambda>
    for chunk in iter(lambda: fileobj.read(1024 * 1024), b''):
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/s3transfer/utils.py", line 480, in read
    data = self._fileobj.read(amount_to_read)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/s3transfer/upload.py", line 86, in read
    return self._fileobj.read(amount)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/s3transfer/utils.py", line 359, in read
    self._open_if_needed()
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/s3transfer/utils.py", line 350, in _open_if_needed
    self._fileobj = self._open_function(self._filename, self._mode)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/s3transfer/utils.py", line 261, in open
    return open(filename, mode)
IsADirectoryError: [Errno 21] Is a directory: './EDGARModel_bert'
[2021-03-23 20:27:42,881] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=Model-Training-Pipeline, task_id=SaveModel, execution_date=20210324T002538, start_date=20210324T002742, end_date=20210324T002742
[2021-03-23 20:27:42,925] {local_task_job.py:146} INFO - Task exited with return code 1
