[2021-03-23 20:28:59,994] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.DownloadDataFromCloud 2021-03-24T03:15:58.972660+00:00 [queued]>
[2021-03-23 20:29:00,001] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.DownloadDataFromCloud 2021-03-24T03:15:58.972660+00:00 [queued]>
[2021-03-23 20:29:00,001] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 20:29:00,001] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-23 20:29:00,001] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 20:29:00,007] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): DownloadDataFromCloud> on 2021-03-24T03:15:58.972660+00:00
[2021-03-23 20:29:00,010] {standard_task_runner.py:52} INFO - Started process 45900 to run task
[2021-03-23 20:29:00,020] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EDGAR-Annotation-Pipeline', 'DownloadDataFromCloud', '2021-03-24T03:15:58.972660+00:00', '--job-id', '99', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/edgar_annotation.py', '--cfg-path', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmp76l1837m', '--error-file', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpys8pl3ij']
[2021-03-23 20:29:00,022] {standard_task_runner.py:77} INFO - Job 99: Subtask DownloadDataFromCloud
[2021-03-23 20:29:00,065] {logging_mixin.py:104} INFO - Running <TaskInstance: EDGAR-Annotation-Pipeline.DownloadDataFromCloud 2021-03-24T03:15:58.972660+00:00 [running]> on host prathyushas-mbp.home
[2021-03-23 20:29:00,094] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EDGAR-Annotation-Pipeline
AIRFLOW_CTX_TASK_ID=DownloadDataFromCloud
AIRFLOW_CTX_EXECUTION_DATE=2021-03-24T03:15:58.972660+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-24T03:15:58.972660+00:00
[2021-03-23 20:29:00,140] {credentials.py:1222} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2021-03-23 20:29:13,020] {python.py:118} INFO - Done. Returned value was: None
[2021-03-23 20:29:13,025] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=EDGAR-Annotation-Pipeline, task_id=DownloadDataFromCloud, execution_date=20210324T031558, start_date=20210324T032859, end_date=20210324T032913
[2021-03-23 20:29:13,042] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-23 20:29:13,063] {local_task_job.py:146} INFO - Task exited with return code 0
